# Generated by Django 5.0.7 on 2024-07-20 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0003_alter_city_count_alter_city_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ("name",),
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.RemoveField(
            model_name="city",
            name="count",
        ),
        migrations.AddField(
            model_name="city",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
