# Generated by Django 5.0.7 on 2024-07-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0004_alter_city_options_remove_city_count_city_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="user",
            new_name="user_id",
        ),
    ]
