# Generated by Django 5.0.7 on 2024-07-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0005_rename_user_city_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ("name",),
                "verbose_name": "city",
                "verbose_name_plural": "cities",
            },
        ),
    ]
