# Generated by Django 5.0.7 on 2024-07-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0007_alter_city_latitude_alter_city_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
