# Generated by Django 5.0.7 on 2024-07-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0008_city_count_alter_city_latitude_alter_city_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
